name: Push Docker Image to ECR

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: arn:aws:iam::443370705000:role/GH-ActionsRole
          role-session-name: DockerImgtoECR
          aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{secrets.ECR_REPO}}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker-compose build
        docker-compose push
