name: Push Docker Image to ECR

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::443370705000:role/GH-ActionsRole
          role-session-name: DockerImgtoECR
          aws-region: us-west-2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get Runner IP address
        id: ip
        uses: haythem/public-ip@v1.3
  
      - name: Whitelist Runner IP
        env:
          AWS_INSTANCE_SG_ID: ${{ secrets.AWS_INSTANCE_SG_ID }}
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 5432 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPO }}
          IMAGE_TAG: latest
          PGADDR: ${{ secrets.PGADDR }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASS: ${{ secrets.PGPASS }}
          GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          GOOGLE_SECRET_ID: ${{ secrets.GOOGLE_SECRET_ID }}
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
        run: |
          docker build \
            --build-arg SPRING_DATASOURCE_URL=jdbc:postgresql://${PGADDR}/db \
            --build-arg SPRING_DATASOURCE_USERNAME=${PGUSER} \
            --build-arg SPRING_DATASOURCE_PASSWORD=${PGPASS} \
            --build-arg GOOGLE_ID=${GOOGLE_ID} \
            --build-arg GOOGLE_SECRET_ID=${GOOGLE_SECRET_ID} \
            --build-arg GH_CLIENT_ID=${GH_CLIENT_ID} \
            --build-arg GH_CLIENT_SECRET=${GH_CLIENT_SECRET}
            -t $REGISTRY/$REPOSITORY-backend:$IMAGE_TAG ./backend
          docker push $REGISTRY/$REPOSITORY-backend:$IMAGE_TAG

      - name: Update ECS Service
        env:
          CLUSTER_NAME: ${{ secrets.ECS_CLUSTER_NAME }}
          SERVICE_NAME: ${{ secrets.ECS_SERVICE_NAME }}
        run: |
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service ${SERVICE_NAME} \
            --force-new-deployment

      - name: Revoke Runner IP address
        env:
          AWS_INSTANCE_SG_ID: ${{ secrets.AWS_INSTANCE_SG_ID }}
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 5432 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
